# Generated by Django 5.2.13 on 2026-04-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'retailer',
                'verbose_name_plural': 'retailers',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('spec', models.CharField(default='', max_length=20, verbose_name='spec')),
                ('brand', models.CharField(max_length=20, verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumption.category')),
            ],
            options={
                'verbose_name': 'commodity',
                'verbose_name_plural': 'commodities',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='note')),
                ('date', models.DateField(verbose_name='date')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumption.commodity')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumption.retailer')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
